# Generated by Django 6.0.1 on 2026-02-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
