# Generated by Django 6.0.1 on 2026-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student_email_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
