# Generated by Django 6.0.1 on 2026-02-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_product_color_product_product_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_subject', models.CharField(max_length=100)),
                ('branch_credit', models.IntegerField()),
                ('branch_duration', models.IntegerField()),
                ('branch_fee', models.IntegerField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
